name: Build & ping sitemaps

on:
  schedule: [ { cron: "12 4 * * *" } ]  # every day 04:12 UTC
  workflow_dispatch:

jobs:
  sitemap:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Build sitemaps
        env:
          SITE_DOMAIN: https://v0-apartment-surveillance-package.vercel.app
        run: node scripts/build-sitemaps.js

      - name: Commit sitemaps
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add public/sitemap.xml public/sitemap-locations.xml
          git commit -m "chore: update sitemaps [skip ci]" || echo "no changes"
          git pull --rebase origin main
          git push

      - name: Ping Google
        run: |
          curl -s "https://www.google.com/ping?sitemap=https://v0-apartment-surveillance-package.vercel.app/sitemap.xml" || true
          curl -s "https://www.google.com/ping?sitemap=https://v0-apartment-surveillance-package.vercel.app/sitemap-locations.xml" || true
